CREATE TABLE Genres(Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(255));
CREATE TABLE Authors(Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, FirstName VARCHAR(255), LastName VARCHAR(255));
CREATE TABLE Books(Id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(255), AuthorId BIGINT, FOREIGN KEY (AuthorId) REFERENCES Authors(Id));
CREATE TABLE BookGenreJoint(BookId BIGINT,  GenreId BIGINT, FOREIGN KEY (BookId) REFERENCES Books, FOREIGN KEY (GenreId) REFERENCES Genres(Id));